name: trna
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - bioconda::bowtie2
  - bioconda::bwa
  - ete3
  - bioconda::fasttree
  - conda-forge::tectonic
  - bioconda::muscle
  - conda-forge::bs4
  - conda-forge::requests
  - infernal
